{
  "formatVersion": "1.1",
  "component": {
    "url": "../../parser-stream/1.0/parser-stream-1.0.module",
    "group": "ru.landgrafhomyak",
    "module": "parser-stream",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "parser-stream.klib",
          "url": "parser-stream-androidnativex64-1.0.klib",
          "size": 11931,
          "sha512": "831971fbc17a51aeb9541242bad1e5267ddfa3c610a64eaada9962ab9ba4686a0e973c6a484b278c871732dfb3bf7411043e510fb2589a632cb03f468bc90864",
          "sha256": "55f85914f82092ab6d65f2413bad85f306b70b42802388898b1f7f06cbd63633",
          "sha1": "5324962962b42129873a6cafc3a0a467a404c5d0",
          "md5": "b378153dc9f91567a61a9de1b58b7935"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "parser-stream-androidnativex64-1.0-sources.jar",
          "url": "parser-stream-androidnativex64-1.0-sources.jar",
          "size": 4129,
          "sha512": "12bba45aa38be852ba2a684544a2b456fa7a5bc9d445d65c2dae35e527d41d61de74f06ef907b2438aaec9aa2f604d3702e47259d6d4c508d33ce98f337fb7df",
          "sha256": "5455454e3d52e6f2ee3f75a0a1ae6bbde82b3ca383b417eeebeb2cb8761cc847",
          "sha1": "31d710d5e442b7a17705293b961fc9d707bbb3b8",
          "md5": "136565a5e41589e78c0f8be19169414c"
        }
      ]
    }
  ]
}
