{
  "formatVersion": "1.1",
  "component": {
    "url": "../../parser-stream/1.0/parser-stream-1.0.module",
    "group": "ru.landgrafhomyak",
    "module": "parser-stream",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "parser-stream.klib",
          "url": "parser-stream-linuxarm64-1.0.klib",
          "size": 11930,
          "sha512": "ae21bde23a9ed9ec60fe4181f7155b2eb06c9c7aa37973be24832eddcad25a7a7b7e6e672f9a7943c92f335fc58d50ae238dd7de4bfcc2c858852074a57fd7a7",
          "sha256": "07bd44899bb6143ead866ab9e94193081a40974f7317670b74f980732cf248dd",
          "sha1": "4145596abeb0d575fde7c46d73ada4faa89d8ac6",
          "md5": "f050ef18968ae85062c9c98ce807efc9"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "parser-stream-linuxarm64-1.0-sources.jar",
          "url": "parser-stream-linuxarm64-1.0-sources.jar",
          "size": 4129,
          "sha512": "12bba45aa38be852ba2a684544a2b456fa7a5bc9d445d65c2dae35e527d41d61de74f06ef907b2438aaec9aa2f604d3702e47259d6d4c508d33ce98f337fb7df",
          "sha256": "5455454e3d52e6f2ee3f75a0a1ae6bbde82b3ca383b417eeebeb2cb8761cc847",
          "sha1": "31d710d5e442b7a17705293b961fc9d707bbb3b8",
          "md5": "136565a5e41589e78c0f8be19169414c"
        }
      ]
    }
  ]
}
