{
  "formatVersion": "1.1",
  "component": {
    "url": "../../parser-stream/1.0/parser-stream-1.0.module",
    "group": "ru.landgrafhomyak",
    "module": "parser-stream",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "parser-stream.klib",
          "url": "parser-stream-linuxx64-1.0.klib",
          "size": 11914,
          "sha512": "f32c81a16dd63ec2440544f2a5505019d74b116322eff6cbb4a8fb009ff21b65697e5a18130cbbd0fe9b5c7783ffe6f8633df1184ba362c2bf0593bcb6cc2d6e",
          "sha256": "c794416a85ac1ed36bcd27f3f49de83e2285ce9bcb8c48563558e0b595641976",
          "sha1": "8c3f3e1daee9e8d638ebb26c1268afb06a2deaab",
          "md5": "9b805aebfddf1d85efe240ab3a72cb53"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "parser-stream-linuxx64-1.0-sources.jar",
          "url": "parser-stream-linuxx64-1.0-sources.jar",
          "size": 4129,
          "sha512": "12bba45aa38be852ba2a684544a2b456fa7a5bc9d445d65c2dae35e527d41d61de74f06ef907b2438aaec9aa2f604d3702e47259d6d4c508d33ce98f337fb7df",
          "sha256": "5455454e3d52e6f2ee3f75a0a1ae6bbde82b3ca383b417eeebeb2cb8761cc847",
          "sha1": "31d710d5e442b7a17705293b961fc9d707bbb3b8",
          "md5": "136565a5e41589e78c0f8be19169414c"
        }
      ]
    }
  ]
}
