{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.landgrafhomyak",
    "module": "parser-stream",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "parser-stream-metadata-1.0.jar",
          "url": "parser-stream-1.0.jar",
          "size": 4882,
          "sha512": "92973e17a10f5e6b729e2594f9f9ed9a329950878e558f94c393b8f21610353ccc46ef681ff73de399a46967e545b470498c128eeb1d2f4c6ac3b326eafc93ba",
          "sha256": "c4c7879dbb834805eb91a9ca1ff305c10ec4543c4ef3eb11ab030932cb8e77e4",
          "sha1": "a999d008668854bb8136bc669125e38f97076728",
          "md5": "8f4ca8573cbd5f0d99a3bbce87b9b112"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "parser-stream-kotlin-1.0-sources.jar",
          "url": "parser-stream-1.0-sources.jar",
          "size": 4129,
          "sha512": "12bba45aa38be852ba2a684544a2b456fa7a5bc9d445d65c2dae35e527d41d61de74f06ef907b2438aaec9aa2f604d3702e47259d6d4c508d33ce98f337fb7df",
          "sha256": "5455454e3d52e6f2ee3f75a0a1ae6bbde82b3ca383b417eeebeb2cb8761cc847",
          "sha1": "31d710d5e442b7a17705293b961fc9d707bbb3b8",
          "md5": "136565a5e41589e78c0f8be19169414c"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-androidnativearm32/1.0/parser-stream-androidnativearm32-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-androidnativearm32",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-androidnativearm32/1.0/parser-stream-androidnativearm32-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-androidnativearm32",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-androidnativearm64/1.0/parser-stream-androidnativearm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-androidnativearm64",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-androidnativearm64/1.0/parser-stream-androidnativearm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-androidnativearm64",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-androidnativex64/1.0/parser-stream-androidnativex64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-androidnativex64",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-androidnativex64/1.0/parser-stream-androidnativex64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-androidnativex64",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-androidnativex86/1.0/parser-stream-androidnativex86-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-androidnativex86",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-androidnativex86/1.0/parser-stream-androidnativex86-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-androidnativex86",
        "version": "1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-iosarm64/1.0/parser-stream-iosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-iosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-iosarm64/1.0/parser-stream-iosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-iosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-iosarm64/1.0/parser-stream-iosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-iosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-iossimulatorarm64/1.0/parser-stream-iossimulatorarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-iossimulatorarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-iossimulatorarm64/1.0/parser-stream-iossimulatorarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-iossimulatorarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-iossimulatorarm64/1.0/parser-stream-iossimulatorarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-iossimulatorarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-iosx64/1.0/parser-stream-iosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-iosx64",
        "version": "1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-iosx64/1.0/parser-stream-iosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-iosx64",
        "version": "1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-iosx64/1.0/parser-stream-iosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-iosx64",
        "version": "1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../parser-stream-js/1.0/parser-stream-js-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-js",
        "version": "1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../parser-stream-js/1.0/parser-stream-js-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-js",
        "version": "1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../parser-stream-js/1.0/parser-stream-js-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-js",
        "version": "1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../parser-stream-jvm/1.0/parser-stream-jvm-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../parser-stream-jvm/1.0/parser-stream-jvm-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../parser-stream-jvm/1.0/parser-stream-jvm-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-linuxarm64/1.0/parser-stream-linuxarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-linuxarm64",
        "version": "1.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-linuxarm64/1.0/parser-stream-linuxarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-linuxarm64",
        "version": "1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-linuxx64/1.0/parser-stream-linuxx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-linuxx64",
        "version": "1.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-linuxx64/1.0/parser-stream-linuxx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-linuxx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-macosarm64/1.0/parser-stream-macosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-macosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-macosarm64/1.0/parser-stream-macosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-macosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-macosarm64/1.0/parser-stream-macosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-macosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-macosx64/1.0/parser-stream-macosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-macosx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-macosx64/1.0/parser-stream-macosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-macosx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-macosx64/1.0/parser-stream-macosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-macosx64",
        "version": "1.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-mingwx64/1.0/parser-stream-mingwx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-mingwx64",
        "version": "1.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-mingwx64/1.0/parser-stream-mingwx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-mingwx64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-tvosarm64/1.0/parser-stream-tvosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-tvosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-tvosarm64/1.0/parser-stream-tvosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-tvosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-tvosarm64/1.0/parser-stream-tvosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-tvosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-tvosx64/1.0/parser-stream-tvosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-tvosx64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-tvosx64/1.0/parser-stream-tvosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-tvosx64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-tvosx64/1.0/parser-stream-tvosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-tvosx64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-watchosarm32/1.0/parser-stream-watchosarm32-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-watchosarm32",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-watchosarm32/1.0/parser-stream-watchosarm32-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-watchosarm32",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-watchosarm32/1.0/parser-stream-watchosarm32-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-watchosarm32",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-watchosarm64/1.0/parser-stream-watchosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-watchosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-watchosarm64/1.0/parser-stream-watchosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-watchosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-watchosarm64/1.0/parser-stream-watchosarm64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-watchosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-watchosx64/1.0/parser-stream-watchosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-watchosx64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-watchosx64/1.0/parser-stream-watchosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-watchosx64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../parser-stream-watchosx64/1.0/parser-stream-watchosx64-1.0.module",
        "group": "ru.landgrafhomyak",
        "module": "parser-stream-watchosx64",
        "version": "1.0"
      }
    }
  ]
}
